# -*- coding: utf-8 -*-
"""Copy of Cleaned the data  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkCrIFTNGBCWhzvI9Tcc0t6g8HgMKIws
"""

pip install pandas requests beautifulsoup4 matplotlib seaborn textblob

import requests
from bs4 import BeautifulSoup

url = "https://salty.co.in/collections/all"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

products = soup.find_all("div", class_="new-product-card__bottom")

print("Products Found:", len(products))

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://salty.co.in/collections/all"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

products = []

cards = soup.find_all("div", class_="new-product-card__bottom")

for card in cards:

    try:
        name = card.find(
            "h3",
            class_="new-product-card__title"
        ).get_text(strip=True)

    except:
        name = ""

    try:
        price = card.find(
            "span",
            class_="new-product-card__price-main"
        ).get_text(strip=True)

    except:
        price = ""

    try:
        old_price = card.find(
            "span",
            class_="new-product-card__price-compare"
        ).get_text(strip=True)

    except:
        old_price = ""

    try:
        discount = card.find(
            "span",
            class_="new-product-card__discount-badge"
        ).get_text(strip=True)

    except:
        discount = ""

    products.append(
        [name, price, old_price, discount]
    )

df = pd.DataFrame(
    products,
    columns=[
        "Product_Name",
        "Price",
        "Old_Price",
        "Discount"
    ]
)

print(df.head())

df.to_csv(
    "salty_products.csv",
    index=False
)

print("CSV Saved Successfully")
import os

print(os.getcwd())



import pandas as pd

df = pd.read_csv("salty_products.csv")

df.drop_duplicates(inplace=True)

df["Price"] = (
    df["Price"]
    .str.replace("Rs.","")
    .str.replace(",","")
    .astype(float)
)

df["Old_Price"] = (
    df["Old_Price"]
    .str.replace("Rs.","")
    .str.replace(",","")
)

df.to_csv(
    "salty_cleaned.csv",
    index=False
)

print(df.head())



import os

print(os.getcwd())

import os

print(os.path.exists("salty_products.csv"))

import os

print("Current Folder:", os.getcwd())

df.to_csv("salty_products.csv", index=False)

df.to_csv(r"C:\Users\Anushka\Desktop\salty_products.csv", index=False)

import os

print(os.listdir())

import os

print(os.listdir())

import os
print(os.getcwd())
print(os.listdir())

from google.colab import files

files.download('salty_cleaned.csv')

from google.colab import files

files.download('salty_products.csv')

"""AI Analysis

"""

from textblob import TextBlob

review = "Amazing quality"

sentiment = TextBlob(review)

print(sentiment.sentiment.polarity)

from textblob import TextBlob

review = "Amazing quality"

score = TextBlob(review).sentiment.polarity

if score > 0:
    print("Positive")
elif score < 0:
    print("Negative")
else:
    print("Neutral")

description = "Premium Rose Gold Diamond Luxury Watch with elegant design"

score = TextBlob(description).sentiment.polarity
print(score)

df["Sentiment"] = df["Product_Name"].apply(
    lambda x: "Positive" if TextBlob(str(x)).sentiment.polarity > 0
    else "Neutral"
)

import requests

url = "https://salty.co.in/collections/all?page=2"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"}
)

print(response.status_code)

import requests
from bs4 import BeautifulSoup
import pandas as pd

all_products = []

for page in range(1,6):   # pages 1 to 5

    url = f"https://salty.co.in/collections/all?page={page}"

    response = requests.get(
        url,
        headers={"User-Agent":"Mozilla/5.0"}
    )

    soup = BeautifulSoup(response.text,"html.parser")

    cards = soup.find_all(
        "div",
        class_="new-product-card__bottom"
    )

    print(f"Page {page}: {len(cards)} products")

    for card in cards:
        name = card.find(
            "h3",
            class_="new-product-card__title"
        ).get_text(strip=True)

        price = card.find(
            "span",
            class_="new-product-card__price-main"
        ).get_text(strip=True)

        all_products.append([name,price])

df = pd.DataFrame(
    all_products,
    columns=["Product_Name","Price"]
)

print(df.shape)

df.to_csv("all_products.csv",index=False)

!pip install selenium
!pip install webdriver-manager

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

print("Installed Successfully")

!pip install selenium
!pip install webdriver-manager

!apt-get update
!apt-get install -y wget unzip
!wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update
!apt-get install -y google-chrome-stable

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

options = Options()
options.add_argument("--headless=new")       # run without a visible window
options.add_argument("--no-sandbox")          # needed when running as root/in containers
options.add_argument("--disable-dev-shm-usage")  # avoids crashes from limited /dev/shm
options.add_argument("--disable-gpu")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

!which google-chrome
!google-chrome --version

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

options = Options()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

driver.get("https://www.google.com")
print(driver.title)

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

options = Options()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(3)  # bump to 4-5 if the site loads slowly
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

print("Finished scrolling")

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from bs4 import BeautifulSoup

options = Options()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

driver.get("https://salty.co.in/collections/all")
sleep(3)

last_count = 0
same_count_repeats = 0

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(4)

    cards = driver.find_elements(By.CLASS_NAME, "new-product-card__bottom")
    current_count = len(cards)
    print("Currently loaded:", current_count)

    if current_count == last_count:
        same_count_repeats += 1
        if same_count_repeats >= 3:
            break
    else:
        same_count_repeats = 0
        last_count = current_count

print("Finished scrolling. Total products:", last_count)

soup = BeautifulSoup(driver.page_source, "html.parser")
final_cards = soup.find_all("div", class_="new-product-card__bottom")
print("Products Found:", len(final_cards))

driver.quit()

options.add_argument("--window-size=1920,1080")

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from bs4 import BeautifulSoup

options = Options()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

all_cards = []
page = 1
max_pages = 176  # from the pagination you saw (1 ... 176)

while page <= max_pages:
    url = f"https://salty.co.in/collections/all?page={page}"
    driver.get(url)
    sleep(2)  # let page render

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div", class_="new-product-card__bottom")

    if not cards:
        print(f"No products found on page {page}, stopping.")
        break

    all_cards.extend(cards)
    print(f"Page {page}: {len(cards)} products (Total so far: {len(all_cards)})")
    page += 1

print("TOTAL PRODUCTS FOUND:", len(all_cards))

driver.quit()

import requests
from bs4 import BeautifulSoup
from time import sleep

all_cards = []
page = 1
max_pages = 176

headers = {"User-Agent": "Mozilla/5.0"}

while page <= max_pages:
    url = f"https://salty.co.in/collections/all?page={page}"
    resp = requests.get(url, headers=headers)
    soup = BeautifulSoup(resp.text, "html.parser")
    cards = soup.find_all("div", class_="new-product-card__bottom")

    if not cards:
        print(f"No products on page {page}, stopping.")
        break

    all_cards.extend(cards)
    print(f"Page {page}: {len(cards)} products (Total: {len(all_cards)})")
    page += 1
    sleep(1)  # be polite to the server

print("TOTAL PRODUCTS FOUND:", len(all_cards))